# Generated by Django 4.2.14 on 2024-08-09 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_product_preparation_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
