# Generated by Django 4.2.14 on 2024-08-09 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_product_colors_remove_product_sizes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsize',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='size_id',
        ),
        migrations.DeleteModel(
            name='ProductColor',
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
    ]
