# Generated by Django 4.2.14 on 2024-08-09 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_productsize_product_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
