# Generated by Django 4.2.14 on 2024-08-09 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_delete_color_delete_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type_attribut', models.IntegerField(unique=True)),
                ('valeur', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Attribut produit',
                'verbose_name_plural': 'Attribut produits',
            },
        ),
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0)),
                ('color', models.ManyToManyField(related_name='products_colors', to='base.productattribut')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_inventory', to='base.product')),
                ('size', models.ManyToManyField(related_name='products_sizes', to='base.productattribut')),
            ],
        ),
    ]
