# Generated by Django 4.2.14 on 2024-08-09 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_productattribut_productinventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinventory',
            options={'verbose_name': 'Inventaire produit', 'verbose_name_plural': 'Inventaire produits'},
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_inventorys', to='base.product'),
        ),
    ]
