# Generated by Django 4.2.14 on 2024-08-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_productinventory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribut',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
