# Generated by Django 4.2.14 on 2024-08-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_productattribut_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribut',
            name='type_attribut',
            field=models.IntegerField(),
        ),
    ]
