# Generated by Django 4.2.14 on 2024-08-10 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_productattribut_type_attribut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='products',
            field=models.ManyToManyField(through='base.CartItemProduct', to='base.productinventory'),
        ),
        migrations.AlterField(
            model_name='cartitemproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.productinventory'),
        ),
    ]
