# Generated by Django 4.2.14 on 2024-08-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_cartitem_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemproduct',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cartitemproduct',
            name='size',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
