# Generated by Django 4.2.14 on 2024-08-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_cartitemproduct_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='used',
            field=models.BooleanField(default=False, help_text='Code promotionnel actif ou inactif'),
        ),
    ]
