# Generated by Django 4.2.14 on 2024-08-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_promocode_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribut',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
